parameters:
    elastification_php_client.transport.http.type.class: GuzzleHttp\Client
    elastification_php_client.transport.http.class: Elastification\Client\Transport\HttpGuzzle\GuzzleTransport
    elastification_php_client.transport.thrift.class: Elastification\Client\Transport\Thrift\ThriftTransport
    elastification_php_client.requestmanager.class: Elastification\Client\Request\RequestManager
    elastification_php_client.client.class: Elastification\Client\Client
    elastification_php_client.logger.class: Elastification\Client\LoggerClient
    elastification_php_client.datacollector.class: Elastification\Bundle\ElastificationPhpClientBundle\DataCollector\ElasticsearchDataCollector

services:
    elastification_php_client.requestmanager:
         class: "%elastification_php_client.requestmanager.class%"
         public: false

    elastification_php_client.datacollector:
         class: "%elastification_php_client.datacollector.class%"
         public: false
         tags:
             - { name: data_collector, template: ElastificationPhpClientBundle:Collector:elasticsearch, id: elasticsearch}
#    elastification_php_client.example:
#        class: Elastification\Bundle\ElastificationPhpClientBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
