parameters:
    elastification_php_client.transport.http.type.class: GuzzleHttp\Client
    elastification_php_client.transport.http.class: Elastification\Client\Transport\HttpGuzzle\GuzzleTransport
    elastification_php_client.transport.thrift.class: Elastification\Client\Transport\Thrift\ThriftTransport
    elastification_php_client.requestmanager.class: Elastification\Client\Request\RequestManager
    elastification_php_client.client.class: Elastification\Client\Client
    elastification_php_client.logger.class: Elastification\Client\LoggerClient
    elastification_php_client.datacollector.class: Elastification\Bundle\ElastificationPhpClientBundle\DataCollector\ElasticsearchDataCollector
    elastification_php_client.profiler.class: Elastification\Bundle\ElastificationPhpClientBundle\Component\ProfilerClient

services:
    elastification_php_client.requestmanager:
         class: "%elastification_php_client.requestmanager.class%"
         public: false

    elastification_php_client.datacollector:
         class: "%elastification_php_client.datacollector.class%"
         public: false
         tags:
             - { name: data_collector, template: ElastificationPhpClientBundle:Collector:elasticsearch, id: elasticsearch}

    elastification_php_client.logger:
         class: "%elastification_php_client.logger.class%"
         arguments: [@elastification_php_client.client, @logger]
         public: false

    elastification_php_client.profiler:
         class: "%elastification_php_client.profiler.class%"
         arguments: [@elastification_php_client, @elastification_php_client.datacollector]
         public: false
